apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: hello CNCF chapter Graz

  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message       # parameter declaration
      container:
        # run cowsay with that message input parameter as args
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]

# resubmit with new parameters:
# argo submit 02-workflow-with-parameters.yaml -p message="goodbye CNCF chapter Graz"